# Generated by Django 5.1.7 on 2025-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('prenume', models.CharField(max_length=30, verbose_name='prenume')),
                ('nume', models.CharField(max_length=30, verbose_name='nume')),
                ('companie', models.CharField(blank=True, max_length=100, verbose_name='companie')),
                ('adresa1', models.CharField(max_length=255, verbose_name='adresa 1')),
                ('adresa2', models.CharField(blank=True, max_length=255, verbose_name='adresa 2')),
                ('oras', models.CharField(max_length=50, verbose_name='oraș')),
                ('cod_postal', models.CharField(max_length=20, verbose_name='cod poștal')),
                ('tara', models.CharField(max_length=50, verbose_name='țară')),
                ('judet', models.CharField(max_length=50, verbose_name='județ')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each group.', related_name='account_set', related_query_name='account', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_user_set', related_query_name='account_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
